name: example
description: An example.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  maps: ^0.2.0
  maps_adapter_google_maps: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

dependency_overrides:
  maps:
    path: ../maps
  maps_adapter_google_maps:
    path: ../maps_adapter_google_maps
  web_browser:
    path: ../../universal_html/web_browser
flutter:
  uses-material-design: true