name: maps
description:
  A cross-platform geographic maps package. Supports Apple MapKit, Bing Maps, and Google Maps. Works
  in all platforms supported by Flutter, including browsers. Now supports NULL-SAFETY!
version: 0.6.0
homepage: https://github.com/dint-dev/maps

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=2.17.0"

dependencies:
  # Maintained by an individual developer.
  # The constraint is fixed for security.
  apple_maps_flutter: ^1.2.0

  # Maintained by Google.
  collection: 1.16.0

  # Maintained by dint.dev team.
  # Contains ECDSA P-256 for signing Apple Maps requests.
  cryptography: ^2.0.5

  # Maintained by dint.dev team.
  # Contains `GeoPoint` implementation we use in this package.
  kind: ^0.5.2

  flutter:
    sdk: flutter

  # Maintained by Google.
  js: 0.6.4

  # Maintained by Google.
  meta: ^1.8.0

  # Maintained by Google.
  url_launcher: ^6.1.7

  # Maintained by dint.dev team.
  web_browser: ^0.5.0

  # Maintained by dint.dev team.
  #web_node: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Maintained by Google.
  flutter_lints: ^2.0.1