name: maps_adapter_google_maps
description: An adapter between 'package:maps' and 'google_maps_flutter'.
version: 0.1.0
homepage: https://github.com/dint-dev/maps

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.0
  maps: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

dependency_overrides:
  maps:
    path: ../maps