name: Dart CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  oursky/flutter:1.17.5

    steps:
      - uses: actions/checkout@v1

      - name: Upgrade Flutter
        run: flutter config --no-analytics && flutter upgrade

      - name: Install dependencies (maps)
        run: flutter pub get
        working-directory: maps

      - name: Install dependencies (maps_adapter_google_maps)
        run: flutter pub get
        working-directory: maps_adapter_google_maps

      - name: Install dependencies (example)
        run: flutter pub get
        working-directory: example

      - name: Run tests (maps)
        run: flutter test --suppress-analytics
        working-directory: maps